### ISSUE TITLE
Support null values in a sorted map

### ISSUE THREAD

**Issue by mattrpav** [atlasmap/atlasmap#107]
For the CombineStrategy, we should support nulls in order to have double-delimiter when an input field value is null.

Looking for assistance on this stream routine to support null values:

```
    protected static Map<Integer, String> sortByKey(Map<Integer, String> map) {
        return map.entrySet().stream()
                .sorted(Map.Entry.comparingByKey())
                .collect(Collectors.toMap(Map.Entry::getKey, Map.Entry::getValue,
                        (oldValue, newValue) -> oldValue, LinkedHashMap::new));
    }
```

**Comment by mattrpav** [comment]
@apupier thoughts?

**Comment by apupier** [comment]
@mattrpav I have not read anything else but one question come to my mind when I read it. Why not using directly a SortedMap?
https://docs.oracle.com/javase/7/docs/api/java/util/SortedMap.html

To be sure, what can be null here are the value of the map provided as parameter?

**Comment by apupier** [comment]
I provided a PR to support null keys: https://github.com/atlasmap/atlasmap/pull/114

For null values here is a bug for Collectors.toMap : https://bugs.openjdk.java.net/browse/JDK-8148463
and i realize that in the title it is mentioning "null values" explicitely...

mightt need to get back to some "old" forEach way to handle the use case

**Comment by apupier** [comment]
I provided another PR supporting both null keys and null values: https://github.com/atlasmap/atlasmap/pull/115

it is using a TreeMap instead of Streams. there might a little performance overhead but seems the more readable code that we can have to handle null values.

What can be thought of is to use the TreeMap all the time to avoid the sort to happens several times. It really depends on the program logic to decide for that. I guess performance measure would need to be handle to be sure.

**Comment by mattrpav** [comment]
Yeah, SortedMap requires an impl, so I was hoping there was some streams magic that'd allow without it. 

<rant>
Java needs the "?" null check operator!  
</rant>

TreeMap sol'n merged.

Thanks!

**Comment by apupier** [comment]
Maybe Stream.ofNullable will help with Java 9 : https://bugs.openjdk.java.net/browse/JDK-8050819
