### ISSUE TITLE
Concatenate and Split multiplicity transformation non-functional for non-string types.

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#1182]
![sc1](https://user-images.githubusercontent.com/2981421/63176880-c1835780-c014-11e9-9871-2f6b82fe32fc.png)

1.  Need to allow concat without a separator so we can create 123456 from 123 and 456.
2.  Need to support split with 123.456 using '.' as the separator.
3,  Do we need the STRING to DOUBLE conversion warning?  They probably already are aware.
4.  Need to allow concat with the '.' separator so we can create 123.456 from 123 and 456.

**Comment by igarashitm** [comment]
I found that we have to think a bit more about this, like do we show `Concatenate` transformation for `NUMBER` type fields after #912? Answer is yes, but not the one we already have because the one we have is for `STRING` type field. We might have to override it for `NUMBER` type fields. This is because we filter transformations with field types. After #912 we'll show `Add` and `Subtract` multiplicity transformations, which should be shown only for `NUMBER` fields.

**Comment by igarashitm** [comment]
Or we might want to change the `Concatenate`/`Split` transformation to accept FieldType.ANY

**Comment by igarashitm** [comment]
This should be addressed by #1207, now Concatenate/Split accept `FieldType.ANY` and values are converted into String through TypeConverter.
