### ISSUE TITLE
pre-cleanup: split css file into 5, base, toolbar, document, mapping-detail and mapping-list(table)

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1193]
This might be a good timing to also split components into sub directories

**Comment by pleacu** [comment]
Hi @seanforyou23, could you review how we split AtlasMap CSS into some component groups? I remember you suggested to have base CSS with only common things defined and let others inherit it, but I don't know how it actually looks like.

 @igarashitm
igarashitm reviewed 3 days ago
ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-app.component.ts
@@ -33,7 +33,11 @@ import { Subscription } from 'rxjs';
  moduleId: module.id,
  encapsulation: ViewEncapsulation.None,
  templateUrl: './data-mapper-app.component.html',
  styleUrls: ['data-mapper-app.component.css'],
  styleUrls: ['data-mapper-base.component.css',
  @igarashitm
igarashitm 3 days ago  • 
 Member
Although I don't yet have clear idea, If I understand correctly @seanforyou23 suggested was to have base CSS to only have global variable definitions and like that, let other CSS inherit that base CSS, then those children CSS is imported by the top component of those sub component groups. For example, toobar component imports toolbar CSS, etc.

  @pleacu
pleacu 3 days ago  • 
 Author Member
@igarashitm @seanforyou23
Ok - here's my quandry...
Lets examine the toolbar component since it's fairly straightforward.
I created:

ui/src/app/lib/atlasmap-data-mapper/components/data-mapper-toolbar.component.css

it includes base:

@import 'data-mapper-base.component.css';

All of the data-mapper-toolbar component css entries are preceded by '.DataMapperUI' so as
to not conflict with anybody who might include the data mapper into their app as a child
app/service (Syndesis).

i.e.: .DataMapperUI .toolbar { margin:1px 0px; padding:10px; }

The main atlasmap app (data-mapper-app.component.ts) does NOT include
data-mapper-toolbar.component.css in its styleUrls. In theory the main atlasmap app
should just include data-mapper-base.component.css.

This fails... (toolbar is all messed up).

What's interesting is that if I remove the '.DataMapperUI' prefix -

i.e.: .toolbar { margin:1px 0px; padding:10px; }

then all is well. The issue seems to be that the DataMapperUI class is defined in the
data-mapper-app.component.html which is not known to the
data-mapper-toolbar.component.css (even though if you inspect the elements you can
see the DataMapper UI class).

I don't want to create an artifical dependency on every component back to the
data-mapper-app.component just to satisfy a css issue. The most straightforward
solution would be to just rename the top-level classes for each major css grouping
and use that -

i.e. .ADMtoolbar { margin:1px 0px; padding:10px; }

That would fix the issue and provide with a non-conflicting CSS name.

WDYT??

**Comment by pleacu** [comment]
Partial fix with PR #1397.  WIll reiterate to reduce size of common and merge common w/ base.
