### ISSUE TITLE
[Regression] Conditional expression is saved into mapping file only when fields are added

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#1264]
When you write conditional expression sequentially i.e:` IF(@number1>@number2, @number3 )` Last bracket `)` will be saved into mapping only when focus is lost from expression input. Until then in json mapping is only" 
```
 "actions" : [ {
            "expression" : "IF(${0}>${1},${2}",
            "@type" : "Expression"
```
which leads to:
```
 Exhausted after delivery attempt: 1 caught: io.atlasmap.api.AtlasException: Errors: [Failed to apply field action: Error processing action Expression - "IF(${0}>${1},${2} - Parse error at line 1, column 28.  Encountered: <EOF>: docId='null', path='null'], 
```

**Comment by igarashitm** [comment]
This is OK for standalone as user have to export mappings which triggers save. But... @pleacu do you know what happens if user hit the save button in Syndesis without focus out from expression? I can't remember what we did for fixing the not saved issue we had with transformation paramter in Syndesis.

**Comment by pleacu** [comment]
I guess in order to select the save button they would have to lose focus from the expression - right?
@mmelko - you're getting this error while you stay in the expression box and once you leave all is well?
This is really the issue we have with evaluating an expression dynamically before the user is done.  We were thinking of having a check box to evaluate it and/or not issue an error but simply underline in red the part of the expression that's in error until the user blurs.

**Comment by igarashitm** [comment]
@pleacu I got the log about it, so the conclusion from syndesisio/syndesis#4874 , we decided to provide instant save for every inputs via #1055. I think we have to get back to this behavior.

**Comment by pleacu** [comment]
ok - I'll look at it.

**Comment by igarashitm** [comment]
So basically while preview is real time, we can't avoid evaluating expression with every user input. If it's annoying, then user have to turn off preview.

Adding `Execute` button for preview instead of this behavior is on the table as an option, but not decided yet. If we do that, we also have to introduce instant expression evaluation apart from preview, just like real time form validation in modern web site, say red dotted underline on expression input box, have a green check mark if it's valid.

**Comment by pleacu** [comment]
Hey @mmelko , @igarashitm - I believe I fixed this issue with this commit 2 weeks ago:

https://github.com/atlasmap/atlasmap/commit/8024184012fd9964b44b4e98d60455d4d7cc44ee#diff-299f817dffff3b3961ddbb7c986dc428

@mmelko - could you give it a try with this ADM?
http://central.maven.org/maven2/io/atlasmap/atlasmap-standalone/1.42.4/atlasmap-standalone-1.42.4.jar

**Comment by igarashitm** [comment]
I tried 1) enable expression 2)edit expression, 3)focus out then mapping json file still had concatenate transformation. I had to select other field and switch active mapping to reflect expression.
