### ISSUE TITLE
Fix circular references in AtlasMap UI

### ISSUE THREAD

**Issue by deeleman** [atlasmap/atlasmap#128]
The following circular dependencies have been found. This might lead to scenarios where a particular dependency is imported as `undefined` from and `import { ... } from '...'` statement:

- [x] src/app/lib/atlasmap-data-mapper/common/data.mapper.util.ts -> src/app/lib/atlasmap-data-mapper/models/config.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/common/data.mapper.util.ts
- [ ] src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts -> src/app/lib/atlasmap-data-mapper/components/line.machine.component.ts -> src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts
- [ ] src/app/lib/atlasmap-data-mapper/components/line.machine.component.ts -> src/app/lib/atlasmap-data-mapper/components/document.definition.component.ts -> src/app/lib/atlasmap-data-mapper/components/line.machine.component.ts
- [x] src/app/lib/atlasmap-data-mapper/models/config.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/models/field.model.ts -> src/app/lib/atlasmap-data-mapper/models/config.model.ts
- [x] src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/models/field.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts
- [x] src/app/lib/atlasmap-data-mapper/models/field.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/models/field.model.ts

**Comment by pleacu** [comment]
@deeleman - Hey Pablo - Paul here (@pleacu) - I was looking at this trivial fcn:
 
https://github.com/atlasmap/atlasmap/blob/master/ui/src/app/lib/atlasmap-data-mapper/common/data.mapper.util.ts#L45

It's causing a circular dependency in several components - I was considering moving it to config.model.ts since it's generating a config.model specific error - wdyt???

**Comment by deeleman** [comment]
@pleacu Hi Paul!

Ideally, a `*.model.ts` file should only store interfaces and abstract classes, but AtlasMapper does not observe common industry standards so `config.model.ts` is as appropriate as any other location.

If you see there're more circular references that are not enlisted above, feel free to edit the issue description and add them to the list, thank you.

**Comment by pleacu** [comment]
- [ x] src/app/lib/atlasmap-data-mapper/common/data.mapper.util.ts -> src/app/lib/atlasmap-data-mapper/models/config.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/common/data.mapper.util.ts

This issue is corrected - ref https://github.com/atlasmap/atlasmap/pull/275/commits/5280b77479c96b57b7b3aae97fb076ebba14fd10

**Comment by pleacu** [comment]
- [x]  src/app/lib/atlasmap-data-mapper/models/field.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/models/field.model.ts

This issue is corrected - ref https://github.com/atlasmap/atlasmap/commit/5c5150ef27026925c71b04c0c2609af7f8eebb93

**Comment by pleacu** [comment]
- [x] src/app/lib/atlasmap-data-mapper/models/config.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/models/field.model.ts -> src/app/lib/atlasmap-data-mapper/models/config.model.ts
- [x] src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts -> src/app/lib/atlasmap-data-mapper/models/field.model.ts -> src/app/lib/atlasmap-data-mapper/models/document.definition.model.ts

This issue is corrected - ref https://github.com/atlasmap/atlasmap/commit/e52168c76ff467dde76f74ab7bb932cb279a24f2

**Comment by pleacu** [comment]
https://github.com/atlasmap/atlasmap/pull/306

the dependency stack goes: lineMachine > docDefInput/ docDefOutput > lineMachine
When you scroll the 'Sources' or 'Targets' document-definition it's necessary to adjust the line mappings.
Instead of calling the lineMachine directly (set up via Angular input) the docDef code now throws a custom event which the lineMachine catches in order to redraw the mapping lines.
