### ISSUE TITLE
Replace tab characters with 4x whitespaces

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#151]
in .java, .xml and .json, tab and whitespace are mixed for indentation. aligh all with 4x whitespaces per one indent.

**Comment by igarashitm** [comment]
hold on a sec, found a test error - may depend on indentation. I'll look into this afternoon

**Comment by igarashitm** [comment]
OK done - it's a huge diff though, I swear I only did eclipse's automagical format!
I needed to revert a few test inputs which caused a test failure due to whitespaces though.
* #152 
* atlasmap/camel-atlasmap#12

**Comment by igarashitm** [comment]
Fixed copyright header

**Comment by rhuss** [comment]
@mattrpav @chirino any objections to merge ? It fixes the issue that many source files have mixed tab and whitespace and since we all use whitespace only (with IDEs automatically adjusting files), PR diffs become quite messy in such a mixed mode.

If you agree, I would like to merge this quickly to avoid rebasing later on.

**Comment by chirino** [comment]
+1

**Comment by igarashitm** [comment]
It may be even better to introduce checkstyle including "tab ban" rule at some point.

**Comment by mattrpav** [comment]
+1 Agreed.  This was on me, thank you for clearing it up!

**Comment by rhuss** [comment]
thanks ! going to merge now ...

**Comment by igarashitm** [comment]
merged
