### ISSUE TITLE
Show dropdown in expression for enum values

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1524]
Show a candidate of enum values in dropdown in expression.

**Comment by pleacu** [comment]
@igarashitm - Hey Tomo - how exactly would this appear in the expression box?  Would it be 

`statesShort.MA`

for the `MA` enum value in the `statesShort` enumeration?
thkx

**Comment by pleacu** [comment]
I can have this as my conditional expression:

`if (name + country-name == "PaulUSA", state, city) `

In this example, `name` and `countryName` appear as fields in the mapping but they are not actually mapped (either `state` or `city` is mapped to the target field).  The blue lines in the UI can appear to indicate that they are referenced as part of a mapping but those fields are in fact not mapped.

<pre>       &quot;expression&quot; : &quot;if (${io.atlasmap.java.test.TargetTestClass:/name} + ${address-enum-schema-c4a44a4b-88d0-4aef-ba71-37720ed20011:/country-name} == \&quot;PaulUSA\&quot;, ${io.atlasmap.java.test.TargetTestClass:/address/state}, ${io.atlasmap.java.test.TargetTestClass:/address/city})&quot;,
        &quot;inputFieldGroup&quot; : {
          &quot;jsonType&quot; : &quot;io.atlasmap.v2.FieldGroup&quot;,
          &quot;actions&quot; : [ ],
          &quot;field&quot; : [ {
            &quot;jsonType&quot; : &quot;io.atlasmap.java.v2.JavaField&quot;,
            &quot;docId&quot; : &quot;io.atlasmap.java.test.TargetTestClass&quot;,
            &quot;index&quot; : 0,
            &quot;path&quot; : &quot;/name&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;name&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.java.v2.JavaField&quot;,
            &quot;docId&quot; : &quot;io.atlasmap.java.test.TargetTestClass&quot;,
            &quot;index&quot; : 1,
            &quot;path&quot; : &quot;/address/state&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;state&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.java.v2.JavaField&quot;,
            &quot;docId&quot; : &quot;io.atlasmap.java.test.TargetTestClass&quot;,
            &quot;index&quot; : 2,
            &quot;path&quot; : &quot;/address/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }, {
            &quot;jsonType&quot; : &quot;io.atlasmap.json.v2.JsonField&quot;,
            &quot;docId&quot; : &quot;address-enum-schema-c4a44a4b-88d0-4aef-ba71-37720ed20011&quot;,
            &quot;index&quot; : 3,
            &quot;path&quot; : &quot;/country-name&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;country-name&quot;
          } ]
        },
</pre>

The issue is that  the UI has no context so it doesn't know `name` and `countryName` are only reference fields.  That's a good thing since adding expression context would add a massive layer of complexity.  As for the dropdown menu for this issue, given this expression:

`if (name + statesShort.AL == "PaulAL", state, city) `

I've got this partial fragment:

        "expression" : "if (${io.atlasmap.java.test.TargetTestClass:/name} + ${io.atlasmap.java.test.TargetTestClass:/statesShort} , ${io.atlasmap.java.test.TargetTestClass:/address/city}, ${io.atlasmap.java.test.TargetTestClass:/address/state})",
        "inputFieldGroup" : {
          "jsonType" : "io.atlasmap.v2.FieldGroup",
          "actions" : [ ],
          "field" : [ {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.java.test.TargetTestClass",
            "index" : 0,
            "path" : "/name",
            "fieldType" : "STRING",
            "name" : "name"
          }, {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.java.test.TargetTestClass",
            "index" : 1,
            "path" : "/address/city",
            "fieldType" : "STRING",
            "name" : "city"
          }, {
            "jsonType" : "io.atlasmap.java.v2.JavaField",
            "docId" : "io.atlasmap.java.test.TargetTestClass",
            "index" : 2,
            "path" : "/address/state",
            "fieldType" : "STRING",
            "name" : "state"
          } ]
        },

@igarashitm - quick questios:
1.  Should the `statesShort` in the `expression` appear like this?  
`${io.atlasmap.java.test.TargetTestClass:/statesShort.AL}`
2. Should the `statesShort` field reference appear as:
        <pre> {
            &quot;jsonType&quot; : &quot;io.atlasmap.java.v2.JavaField&quot;,
            &quot;docId&quot; : &quot;io.atlasmap.java.test.TargetTestClass&quot;,
            &quot;index&quot; : 1,
            &quot;path&quot; : &quot;/address/city&quot;,
            &quot;fieldType&quot; : &quot;STRING&quot;,
            &quot;name&quot; : &quot;city&quot;
          }</pre>

WDYT??

**Comment by igarashitm** [comment]
I think we need runtime support for this, currently expression parser doesn't recognize enum value. It would have to be a static value rather than a field, so we can't really use `${}`.

**Comment by igarashitm** [comment]
I wonder, can we put just a value of the enum as a string literal once selected, so it could be handled as a string literal in expression parser? It should be fine then with current backend.

**Comment by pleacu** [comment]
Sounds like a good idea.

**Comment by pleacu** [comment]
@igarashitm - Hey - I've got the UI finally straightened out for this.
The user selects `statesLong.Alabama` in the expression box and then selects `Massachusetts` from the pull-down menu.  I can't use the string literal - i.e.:

`${io.atlasmap.java.test.TargetTestClass:/statesLong.Massachusetts}` would just be `"Massachusetts"` because I need to re-establish the `statesLong.Massachusetts` when I deserialize the expression on startup.

 I'd like to keep the ${} syntax so it can be consumed by the UI.  Is there any way we can modify the syntax for an enumeration assigned value?  Something like:

<pre>&quot;expression&quot; : &quot;if (${io.atlasmap.java.test.TargetTestClass:/name}+ ${io.atlasmap.java.test.TargetTestClass:/statesLong<5>}, ...</pre>

Where `<5>` for an enumeration represents the assigned value index?  It would then appear as `statesLong.Massachusetts` in the expression box.

**Comment by igarashitm** [comment]
That would require a bigger surgery at runtime side, and might need a whole enum dictionary embedded into mapping definition.
But I think it's OK to keep it as string literal, no need to re-establish `StatesLong.Massachusetts` once it's embedded into expression. So just to be a input assist for the literal value, but after it's put we forget that it's an enum.

**Comment by pleacu** [comment]
Ok - sounds good.

**Comment by igarashitm** [comment]
Note for the 2nd shot in the future - in order to keep an enum value as a variable in the expression, we need an enum dictionary or a hidden value store in mapping definition. Although Java class - i.e. schema - is always accessible through an instance, that's not same for JSON/XML, we have to explicitly provide schema info for runtime. And then, all module supports enum (Java/JSON/XML) needs an enhancement to parse dot notation `.` in the path as a way to specify an enum value, then each module looks for a value in the dictionary or value store in the mapping definition.

**Comment by pleacu** [comment]
Starting with an expression involving an enum field:

![sc1](https://user-images.githubusercontent.com/2981421/112515336-90c8df80-8d6c-11eb-862d-20f29dd06b4c.png)

Click on the enum field `statesLong`:

![sc2](https://user-images.githubusercontent.com/2981421/112515516-b48c2580-8d6c-11eb-9e4c-135d830ad8ee.png)

Select `Massachusetts` from the drop-down select menu.  The expression field is updated to `statesLong.Massachusetts`.  Users may click on the enum as often as desired to change the value before leaving the Atlasmap session.

![sc3](https://user-images.githubusercontent.com/2981421/112515605-c968b900-8d6c-11eb-8339-08a9f5e37719.png)

Upon restarting the tool or exporting/importing, the string literal is used instead of the enumeration field name.

![sc4](https://user-images.githubusercontent.com/2981421/112515965-27959c00-8d6d-11eb-8b13-5d4a49a1eb10.png)

ref: https://github.com/atlasmap/atlasmap/blob/master/ui/test-resources/adm/enumtest.adm
