### ISSUE TITLE
regression: older .adm file fails to be loaded

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#1590]
Importing this .adm file ends up with empty mapping
https://github.com/atlasmap/atlasmap/blob/master/examples/camel-example-atlasmap-blueprint/src/main/resources/atlasmap-mapping.adm

**Comment by AbbassFaytaroony** [comment]
@igarashitm i checked this now, thankfully it is not caused by my change ;) . This is happening because mapping file inside the ADM is named `atlasmapping.json`, although mapping definition name in the file is `"UI.454150"` , causing the catEntry to be ignored. 
Pushing it along with #1588 in few hours.

**Comment by igarashitm** [comment]
Oh great, thanks! yep there're some wacky case we have to support due to earlier version.
