### ISSUE TITLE
[VS Code] 'Create new mapping' button is not working inside VS Code UI

### ISSUE THREAD

**Issue by apupier** [atlasmap/atlasmap#2054]
- open AtlasMap
- import a source (from an xml file for instance)
- import a target (from the same xml file for instance)
- on one of the field in source, click on the top-right button for it `Create new mapping`
  --> nothing happens, the right panel is not opening, there is no error in console log

![cerateNewMappingNotWorking](https://user-images.githubusercontent.com/1105127/81649295-5eeaab00-9430-11ea-9fc1-01b0b73de1b7.gif)

**Comment by apupier** [comment]
it is working using Chrome.

I reproduced with this example https://github.com/atlasmap/atlasmap/blob/master/standalone/src/test/resources/json-schema-source-to-xml-schema-target.adm used in AtlasMap tests

**Comment by apupier** [comment]
workaround:
- click on the line
- navigate with tab to the "mapping" button
- click enter

**Comment by riccardo-forina** [comment]
I spent a good chunk of time on this today and I can say that the issue is in the iframe nesting that is causing some issues:
- there is no console.log, and the dev tools inspector can't inspect AtlaMap's iframe at all
- single clicking on the fields icons doesn't work (but double-clicking them works for reasons)
- drag & drop, you can start dragging but it stops immediately

I have the feeling something else could be broken.

I then tried loading AtlasMap by injecting the required js files directly and it works, but because of how the standalone app is packaged it's not a straight-forward change.

I'll update this or open a PR when I have news.
