### ISSUE TITLE
Multiplicity transformation argument label needs formatting

### ISSUE THREAD

**Issue by pleacu** [atlasmap/atlasmap#2087]
It used to look like this:
![sc2](https://user-images.githubusercontent.com/2981421/82456246-fb8cf880-9a81-11ea-80e6-96f12b4aaf3d.png)
It now looks like this:
![sc1](https://user-images.githubusercontent.com/2981421/82456400-2d05c400-9a82-11ea-8203-0874d1c58e88.png)

**Comment by riccardo-forina** [comment]
It’s a deliberate change actually, labels rendered that way don’t scale in some cases like when converting units.

**Comment by pleacu** [comment]
It appears awkward with the transformation - maybe a left margin on the argument to match the transformation?

**Comment by gashcrumb** [comment]
or maybe a bit more padding to the top and bottom of the label to help distinguish it as such?  I guess the other thing making stick out is that those two controls aren't grouped in a box like the ones below.

**Comment by riccardo-forina** [comment]
Cc @dongniwang

**Comment by dongniwang** [comment]
Can someone please highlight the part we're discussing in the screenshot so I know for sure which label we're talking about? Thank you!

**Comment by pleacu** [comment]
![sc1a](https://user-images.githubusercontent.com/2981421/82463946-77d80980-9a8b-11ea-9761-629950ac5b80.png)

**Comment by riccardo-forina** [comment]
@dongniwang in PR #2085 I changed the "transformation" widget to look from this:
https://deploy-preview-2065--atlasmap.netlify.app/?path=/story/ui-mapping-details-transformation--example

to this:
https://atlasmap.netlify.app/?path=/story/ui-mapping-details-transformation--example

The motivation behind the change is that in some cases like unit transformation (eg. km to miles) labels where long enough to break the layout of the [`InputGroup` component I used](https://www.patternfly.org/v4/documentation/react/components/inputgroup) which was an error in first place since it's not meant to show labels.

Since the multiplicity transformation - aka the screen Paul shared, which is about the transformation applied to the whole mapping in a one-to-many or in a many-to-one scenario - under the hood uses the same widget as the fields' transformations, the change applied there too.

Overall I think how it is now it's the correct way, but I agree we could show and explain better the multiplicity part of the UI. Like as a section with maybe some help text to explain what it is.

**Comment by dongniwang** [comment]
@riccardo-forina @pleacu Thanks for the update. 

1. Just looking at the spacing for the input fields in the screenshot, we need to have a 24px spacing underneath every form input. See[ PF guideline here](24px spacing underneath every form input) for details. 
2. Re the transformation widget, I was not able to provide feedback in the PR, sorry about that. But I think this is a use case we didn't document? Do we have a feature story around this somewhere? I need to read through the comment and think more about this to so that I can come up with a suggestion.

**Comment by riccardo-forina** [comment]
I don't think there is a feature story, it's a direct port from the old Angular UI.

**Comment by riccardo-forina** [comment]
I was checking the link you shared and the available components and I'm not sure how to present fields that are logically grouped together. In plain HTML I'd use a [fieldset](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/fieldset) but I don't see an equivalent in PatternFly.

I tried real quick to apply the correct spacing and the general look becomes this:
![image](https://user-images.githubusercontent.com/966316/82474083-d1abf400-9aca-11ea-9182-19ed7bd5261b.png)

Note that the transformations boxes is something we made custom, and we are not using them for the multiplicity widget.
