### ISSUE TITLE
Input field types are not validated in transformations

### ISSUE THREAD

**Issue by mmelko** [atlasmap/atlasmap#230]
Lets say we have mapping between `String` types field. When "Concatenate" is added as transformation  warning/error that "Input must be a Collection, Map or array" should be thrown. 
Or better -> "Concatenate" shouldn't be listed in transformations for this particular mapping.

**Comment by igarashitm** [comment]
To achieve it we need to distinguish the field action which **only** supports collection from the one supports both of collection and non-collection. That might require a refactoring on the field action annotation. @jpav WDYT?

**Comment by jpav** [comment]
I completely agree. I was thinking about this before the break when I was working on filling out the actions. I think we need more metadata available that we can specify to indicate when and where actions should be available so they are only listed in the available transformation for a particular mapping when appropriate, as @mmelko suggested in his initial comment.

**Comment by igarashitm** [comment]
Also note that the Collection field itself is not a mappable field, but it's yet another type of field container. We need to solve #210 ahead to receive a collection field as a whole into field action.

Also IIRC, in order to enable Collection->non-Collection field action, we'll need to enable source side field action. Let's say we have `concat` which supports String[]->String, target field type needs to be String, but the target side field action only can apply the field actions taking String as an input. Correct @jpav ?

**Comment by igarashitm** [comment]
Let's separate the discussion, I would +1 to focus on, by default, leaving the field empty in UI here, then keep discussion for the empty vs. null in #243.

**Comment by igarashitm** [comment]
addressed by #1144
