### ISSUE TITLE
Do not show multiplicity transformation dropdown if expression is enabled

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2415]
If expression is enabled on many-to-one mapping, multiplicity transformation dropdown stays in Mapping Details, but it won't be used at runtime.

**Comment by pleacu** [comment]
Fixed by https://github.com/atlasmap/atlasmap/commit/a35fb196b5d00b31e6ca9998a1f1bb25dc6b2409
The multiplicity transformation dropdown disappears entirely if the user toggles on the expression box:

![sc1](https://user-images.githubusercontent.com/2981421/95901760-d31fd680-0d61-11eb-871a-226f5dd557e5.png)

![sc2](https://user-images.githubusercontent.com/2981421/95901783-d9ae4e00-0d61-11eb-8983-6d87adaa00f6.png)

**Comment by igarashitm** [comment]
Duplicate of #2412
