### ISSUE TITLE
Support changing document name

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2433]
ATM document name is automatically assigned from file name (JSON, XML, CSV) or class name (Java). We have to allow user to change displaying document name so that user can assign semantic name. For example you have a schema `address.xsd`, and want to have 3 distinct source documents from this same schema, like `US address`, `EMEA address` and `APAC address`.
Document ID has to be preserved on the other hand.
Also, in Syndesis, this feature has to be disabled. We might need a flag in UI build settings to enable/disable it just like we do for import/export.

**Comment by pleacu** [comment]
@igarashitm - so how would this work?  The user imports `address.xsd` - they then select a new button `Change document name` where it changes the document `name` field but not the document ID?  Why wouldn't they create separate documents?  How would they create multiple documents from the same imported xsd?  Need more details...

**Comment by igarashitm** [comment]
It would be simply click the document title and edit, so that user can assign whatever they like. User defined display name allows them to visually distinguish them in soruces/target panel as well as among scoped properties.
1. Import address.xsd
1. Change the imported document name to "US address"
1. Import address.xsd
1. Change the 2nd imported document name to "EMEA address"
...

**Comment by pleacu** [comment]
@riccardo-forina - question for you.  As Tomo has specified above, I need to support having the user edit the document names by clicking them.  Currently a click on the name results in toggling expand - I can move that so that only clicking on the arrow next to the name toggles the expand.  As for editing the document name in-line - is using something like this the best way to go?

https://www.patternfly.org/v4/components/inline-edit/design-guidelines#field-specific-edit

I don't really like the pencil icon - can it not exist and then simply clicking the name moves you into an edit widget?

wdyt?

**Comment by riccardo-forina** [comment]
I think it needs an icon because any action needs to be explicitly available for a11y reasons. Just clicking the name wouldn't be enough for, eg. keyboard only users.

**Comment by pleacu** [comment]
@riccardo-forina - So you would suggest a separate edit-name icon next to the capture name and delete icons.

**Comment by riccardo-forina** [comment]
Yes exactly.

**Comment by pleacu** [comment]
![sc1](https://user-images.githubusercontent.com/2981421/97877072-acaee480-1cea-11eb-9e6a-0051bad1cdbf.png)
![sc2](https://user-images.githubusercontent.com/2981421/97877080-b0426b80-1cea-11eb-8ee9-e710ea9c9c2f.png)
![sc3](https://user-images.githubusercontent.com/2981421/97877090-b3d5f280-1cea-11eb-8721-f2551b9a2b51.png)
