### ISSUE TITLE
@ should show or not be needed in function expressions

### ISSUE THREAD

**Issue by jpav** [atlasmap/atlasmap#2539]
Currently, when a user enters a function expression, they need to precede field references with an @. However, once they field is selected, the @ symbol is no longer shown. This is confusing in that it makes it appear as if field names can be entered without the @. We should either always show the @ symbol or remove its necessity, allowing the automatic distinction between field and function (e.g., IF, ISEMPTY) names based on whether names are followed by a left parenthesis.

**Comment by pleacu** [comment]
We can't really wait until the user types a '(' to determine that the previous name is a field name.  We need to present the dropdown  select menu so they can select the actual field if the same name is used in different subfolders.  We use the '@' to trigger the select menu and then decorate the field by using a bold font (and dropping the '@' as superfluous).

**Comment by jpav** [comment]
I fully agree with your first statement. As with almost any other tool with content assist, including our own IDEs, I'd argue the established user expectation is as soon as a character is pressed, a content assist menu would offer all possibilities based upon what has been typed. Thus, if 'if' were quickly typed, the content menu would show both all functions that contain 'if', along with a separator and all fields that contain 'if'. There is nothing to tell the user to type an '@' to begin with, and it's misleading when existing field name don't show an '@' was required. It appears as if just typing the name should suffice, which I'd argue is exactly what we should provide.

**Comment by igarashitm** [comment]
Showing `@` permanently for field reference is confusing for me. We are using it as a temporary control character to trigger field auto completion. We should show the established field as a label instead.

**Comment by jpav** [comment]
I'm actually advocating to not show it at all. Auto-completion should just be based on the user typing characters, as I explained above. The need to type the @ sign and not showing it is a significant usability issue I believe. Do you mind if I get feedback from the UX team?

**Comment by jpav** [comment]
@amysueg Would there be someone from the UX team that could weigh in on this?

**Comment by amysueg** [comment]
Is it possible for me to actually try this out somewhere @jpav @pleacu ? Not sure I'm getting the nuance the way I would with a hands-on experience.

**Comment by pleacu** [comment]
`wget https://repo1.maven.org/maven2/io/atlasmap/atlasmap-standalone/2.1.5/atlasmap-standalone-2.1.5.jar`
`java -jar ./atlasmap-standalone-2.1.5.jar`

* In your favorite browser...
`http://localhost:8585/`

* In AtlasMap - download a source and target document, i.e.
`wget https://raw.githubusercontent.com/atlasmap/atlasmap/master/ui/test-resources/json/schema/mock-json-schema.json`

* On the Source panel - import `./mock-json-schema.json`
* On the Target panel - import `./mock-json-schema.json`

* Create a mapping from `primitives/stringPrimitive` to `primitives/stringPrimitive` (as an example)

* Select the `f(x)` button in the conditional mapping expression box (top left)

Within the expression box - type ` + @`.  You'll see a drop-down menu appear with all selectable fields.  In the example - I select  `addressList<>/state`.  Once selected - `state` appears in bold font within the expression to identify that it is a field.

The issue is that entering the `@` character is the method we've chosen for the user to add fields to the expression box.  The UI relies on the runtime to parse the expression and consequently has no context.  The `@` is the method we used in the old angular UI.  Since entering one character would trigger the drop-down I would find it confusing since expression characters for `IF`, `ISEMPTY` for example or for built-in functions `lcase` would cause a drop-down to appear.

My opinion is to not show the `@` permanently and to keep it as our way of indicating the user is asking for a field, not a function.  If I want to lowercase and I type `lca` I don't want auto-complete to find all of my fields that start with `lca` and having a separate add function button would be confusing.

**Comment by jpav** [comment]
@pleacu I'm sorry if I misconstrued, but I'm not suggesting to have a separate button to add content, be it functions or fields. The functionality of the f(x) button itself is a separate concern, but like this issue, I would expect it to act as that button does in all other popular spreadsheets with this functionality. That aside, typing 'lca' and getting a dropdown showing all constructs that begin with 'lca', be they fields or functions, is exactly what the expectation would be of the user. This isn't just me throwing that out there, but is well established is almost all tools that provide some sort of content assist, be it spreadsheets like Microsoft Excel, Apple Numbers, and Google Sheets, or tools like our IDE's, like Eclipse, VS Code, etc. This type of behaviors has become the defacto standard for users, and thus now matches the user's mental model. Expecting the user to type an '@' when there is no indication in AtlasMap that that is required, especially given we don't show it for existing field references, is definitely going to confuse users. We have to pick one way or the other, either require it and show it, or don't require it (as content assist should be sufficient) and don't ever show it. Trying to require it and not showing it just not user-friendly and contradicts established expectations, for both developers and citizen users.
