### ISSUE TITLE
XML collection field is not handled as expected

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2566]
With this XML schema, `item` should be a collection - https://github.com/atlasmap/atlasmap/blob/master/lib/modules/xml/core/src/test/resources/inspect/po-example-schema.xsd

but the collection indication like `[]` or `<>` is not added to the path. And UI doesn't show it as a collection even if collectionType=LIST. Not sure if UI depends on those collection indicator in the path or not.

**Comment by pleacu** [comment]
I couldn't import the xsd you specified above.  Validation errors like:

<pre><font color="#1E8C32">2021-02-10 15:08:10.918 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">9498</font> --- [  XNIO-1 task-1] <font color="#06989A">io.atlasmap.service.AtlasService        </font> : createMappingRequest (save) with format &apos;GZ&apos;
<font color="#1E8C32">2021-02-10 15:08:10.919 </font><font color="#6AC911">DEBUG</font> <font color="#75507B">9498</font> --- [  XNIO-1 task-1] <font color="#06989A">io.atlasmap.service.AtlasService        </font> :   saveGzippedADMDigestRequest &apos;adm-catalog-files-0.gz&apos; - ID: 0
[Fatal Error] :136:5: The element type &quot;link&quot; must be terminated by the matching end-tag &quot;&lt;/link&gt;&quot;.
<font color="#1E8C32">2021-02-10 15:09:31.018 </font><font color="#CC0000">ERROR</font> <font color="#75507B">9498</font> --- [  XNIO-1 task-1] <font color="#06989A">io.atlasmap.xml.service.XmlService      </font> : Error inspecting xml: io.atlasmap.api.AtlasException: org.xml.sax.SAXParseException; lineNumber: 136; columnNumber: 5; The element type &quot;link&quot; must be terminated by the matching end-tag &quot;&lt;/link&gt;&quot;.
</pre>

But I have my own version of `po-example-schema.xsd`.  It seems to work okay with my fix for https://github.com/atlasmap/atlasmap/issues/2571

![sc1](https://user-images.githubusercontent.com/2981421/107566423-e4171200-6bb2-11eb-9398-cb4501a27c5b.png)

@igarashitm - will allow you to double check if you'd like otherwise will close as dupl of 2571

**Comment by igarashitm** [comment]
Duplicate of #2571
