### ISSUE TITLE
Unnecessary empty `value` on each mapping fields

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#2707]
Now UI generates mapping definition with empty `value` on all mapping field, no matter if it's constant or not. Runtime doesn't care, but it's confusing when a human looks at the mapping definition. We should remove `value` from all non-constant mapping fields. Although Constant is an exception, we might also remove constant value from mapping field due to #2706. 
```json
    "mappings" : {
      "mapping" : [ {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputField" : [ {
          "jsonType" : "io.atlasmap.v2.ConstantField",
          "value" : "",
          "docId" : "DOC.Constants.760088",
          "path" : "/testv",
          "fieldType" : "STRING"
        } ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.json.v2.JsonField",
          "value" : "",
          "docId" : "JSONSchemaSource-50a01b0d-e834-4eec-9ad7-d71ddb117328",
          "path" : "/primitives/stringPrimitive",
          "fieldType" : "STRING",
          "name" : "stringPrimitive"
        } ],
        "id" : "mapping.167313"
      }, {
        "jsonType" : "io.atlasmap.v2.Mapping",
        "inputField" : [ {
          "jsonType" : "io.atlasmap.json.v2.JsonField",
          "value" : "",
          "docId" : "JSONSchemaSource-4a377e0b-7d77-4280-94be-30e2899dd57c",
          "path" : "/primitives/booleanPrimitive",
          "fieldType" : "BOOLEAN",
          "name" : "booleanPrimitive"
        } ],
        "outputField" : [ {
          "jsonType" : "io.atlasmap.json.v2.JsonField",
          "value" : "",
          "docId" : "JSONSchemaSource-50a01b0d-e834-4eec-9ad7-d71ddb117328",
          "path" : "/primitives/booleanPrimitive",
          "fieldType" : "BOOLEAN",
          "name" : "booleanPrimitive"
        } ],
        "id" : "mapping.544771"
      } ]
    },
```

**Comment by pleacu** [comment]
Actually the runtime does care when preview mode is on.  The UI must pass an empty string (not null) which occurs when the user first enables preview mode (otherwise we get an unexpected null error from RT).  Also - React will issue a render error if `value` is referenced and is `null` or `undefined`.  So - the latest tweek to the UI serializer for #2706 seems to get as close as we can get.  When a user first establishes a mapping the `value` field is *not* defined.  If the user enables preview mode then an empty string is provided until they enter something.  If they toggle the preview mode button then they still retain the value.  I don't want to set the value field to `undefined` or `null` since it may trigger a React error (on render or on d&d).  We have minimal testing coverage (working on that...)

**Comment by igarashitm** [comment]
I mean runtime doesn't care if mapping field has value, it just ignores. The preview request is reusing same model, but it's a different object which does have field value. We might want to separate preview request model objects from mapping definition at design level if it's confusing.

**Comment by pleacu** [comment]
correct - except for constants.  I think it's pulled apart ok now.

**Comment by pleacu** [comment]
Corected via https://github.com/atlasmap/atlasmap/pull/2709
