### ISSUE TITLE
[RFE] Investigate creating a library to leverage Apache Kafka single message transforms

### ISSUE THREAD

**Issue by gashcrumb** [atlasmap/atlasmap#3182]
The Kafka connect API contains among other things an [interface for doing transformations on messages](https://www.confluent.io/blog/kafka-connect-single-message-transformation-tutorial-with-examples/) as they flow from sources to sinks.  It'd be interesting to see if we could leverage these interfaces to allow users to define these transformations in AtlasMap.

**Comment by igarashitm** [comment]
Glueing data shapes for this usecase is something we have to consider well it seems like. There could be 2 options:
#### Serialized JSON/XML/CSV as a single key/value
In this case kafka schema is not involved and instead the schema has to be fed into AtlasMap UI individually. For example, using `FileStreamSource` connector, a record is sent for each line in the input file, having the text data as a value with null key. Although this case leverages AtlasMap's cross format data mapping feature, it doesn't look like a common usage for kafka.
#### kafka structured data as a key and a value
The kafka connect can set up a converter to serialize/deserialize from/to kafka internal data structure. We'll need to create a kafka AtlasMap module and let it handle the mapping between kafka data structure and AtlasMap one. It would be simpler/smaller than others like JSON/XML since kafka's is very similar to what AtlasMap do with AtlasMap `Field`. e.g. The kafka `Struct` is an equivalent to `FieldType.COMPLEX` in AtlasMap. 
How the schema is passed into AtlasMap is a question, especially in AtlasMap UI. It is recommended to use Confluent schema-registry to manage kafka schema. Putting integration with the schema-registry aside, for the 1st attempt, we would assume the user would manually load the schema into AtlasMap UI just like we expect in standalone usage today. But even so, we'd have to support Avro schema and protobuf schema in AtlasMap.
Also, instead of deliverying kafka record as a single AtlasMap `Document`, key and value are better to be handled as a separate `Document` as they have dedicated kafka runtime schema maintained for each, attached to the record. We'd need to investigate how we can attach those kafka runtime schema as a generic runtime `Document` metadata into AtlasMap context.
Or kafka schema might not really required for AtlasMap runtime? in theory all the schemas are already fed into AtlasMap UI at design time, so at runtime there shouldn't be a need for updating schema but the design time schemas could be used as-is for both of source and target.
In this usecase, AtlasMap has to internally use `KafkaField` that handles kafka data structure like `Struct`. AtlasMap never knows the real data format, e.g. JSON, CSV, XML - seralize/desrialize is done by kafka connect. That means plain Avro support in AtlasMap if there is, would be a different implementation than kafka Avro support.
#### Fact
We would assume that, whichever the schemas are kafka aware or only for AtlasMap, they are loaded into AtlasMap UI. And it has to distinguish if it's kafka aware or serialized into kafka key or value.
