### ISSUE TITLE
[BUG] CSV import is broken

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#3390]
xref: https://issues.redhat.com/browse/ENTESB-17416

**Describe the bug**
Importing CSV as a Document shows only one field and header is ignored.

**Attach .adm file and source document examples**
example CSV
```csv
sourceCsvString,sourceCsvNumber,sourceCsvDecimal,sourceCsvDate,sourceCsvBoolean
csv0,0,0.0,1989-05-05,true
csv1,10,10.0,1989-05-05,true
csv2,20,20.0,1989-05-05,true
csv3,30,30.0,1989-05-05,false
csv4,40,40.0,1989-05-05,false
```
 
**Attach debug logs**
backend log doesn't show nothing special
![Screenshot from 2021-10-12 07-27-18](https://user-images.githubusercontent.com/265462/136948181-2df31b45-0e4d-42f9-92b3-6da3ad757666.png)
![Screenshot from 2021-10-12 07-27-46](https://user-images.githubusercontent.com/265462/136948196-9b185236-6e53-4a8e-9c4d-5557429cab36.png)

 
**To Reproduce**
1. Import CSV
2. Add `Delimiter` parameter with `,`
3. See error

**Expected behavior**
5 CSV fields have to show with name from header.

**Comment by igarashitm** [comment]
The inspection parameters received at backend are all null including delimiter and header. Something wrong at UI side.

**Comment by pleacu** [comment]
I'll take a look at the UI

**Comment by pleacu** [comment]
@igarashitm - so - this is where the document inspection takes place. 

![scd1](https://user-images.githubusercontent.com/2981421/136998790-4283ad69-549e-4f4e-a379-eab05ff2e019.png)

Here's the inspection response:

![scd2](https://user-images.githubusercontent.com/2981421/137000746-c389e047-2833-48be-ba55-35e76ce38e65.png)

Since the RT is parsing the CSV body already and returning the complex fields - I think the correct place to parse the CSV params is in the RT and have it return a correct parse response to the UI.  I can then generate the correct InputFieldGroup/inputFields in the mapping based on that.
