### ISSUE TITLE
Support exporting mapping definition file in standalone UI

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#377]
To make fair sense with standalone UI, we should support saving mapping definition. ATM mapping definition is only found in working directory of design time services.

**Comment by pleacu** [comment]
Quick demo:

https://bluejeans.com/playback/s/ribrjgDi81WD136sPUHQ1TPLapi26wnI3NakFQ5KlepoLVhgZN1s8ey6sl4AlWSy

**Comment by deernano** [comment]
@pleacu Hi paul, I saw your video, I will provide a UI refined wireframe file for you in these two days.
Thanks!

**Comment by deernano** [comment]
@pleacu 
Hi Paul, from UX point of view, the overall function is quite accurate, there are just small UI issues that I would like to propose to you:
1. Button position
From the video, there are two places to activate the import/export function:
a. Banner
b. Source/target box
I would like to propose another position to avoid duplication. Since most of our action buttons are on the top right. We can place the import/ export button to the same row of the other action buttons.
If we place the icons on header, they are a bit far from the source/ target box. Thus, the user may loosing focus. The clicking are for 'b' method is a bit small.
Here are some references from Patternfly and other products:
[PF-View Selector](https://www.patternfly.org/pattern-library/forms-and-controls/view-selector/#overview)
[Ovirt](https://github.com/oVirt/ovirt-design/blob/dbcbd2e3bace3567c431a6166041f5aaeddc4bf1/user-portal/snapshots.md)

![import-export1 2x](https://user-images.githubusercontent.com/5396309/44522594-a8014580-a709-11e8-8060-adf93f9e5560.png)

The tooltip will be the same but adding a hover status (highlighted)

![import-export2 2x](https://user-images.githubusercontent.com/5396309/44523137-725d5c00-a70b-11e8-806c-f0011560442e.png)

2. Using pop up instead of dropdown menu
Since we have some actions that need the user to choose from, it is better to user pop than the dropdown menu. (Same as the user switching mapping)
![import-export3 2x](https://user-images.githubusercontent.com/5396309/44523223-bfd9c900-a70b-11e8-9895-21bf69f0fc6d.png)

3. Confirm all actions
It is better to let the user confirm all actions. So I add a check mark beside the selected file format.

![import-export4 2x](https://user-images.githubusercontent.com/5396309/44523294-eef03a80-a70b-11e8-9112-9f7a8969a13c.png)

Also, the user need to click 'Continue' to confirm all actions.
Refference: [PF-Message Dialogs](https://www.patternfly.org/pattern-library/communication/message-dialog/)

![import-export5 2x](https://user-images.githubusercontent.com/5396309/44523315-03343780-a70c-11e8-87cb-1068bc4169a6.png)

![import-export6 2x](https://user-images.githubusercontent.com/5396309/44523352-1e9f4280-a70c-11e8-9080-adaf1b5382a1.png)

4. Automatic expand & Toast notification
a. When the file is imported, it is better to collaspe the opened file and expand the imported file. This could avoid users scrolling down and loosing focus.
b. When the file is imported/ exported, it is better to use a toast notification to inform the user.
Refference: [PF-Toast Notification](https://www.patternfly.org/pattern-library/communication/toast-notifications/#overview)

![import-export7 2x](https://user-images.githubusercontent.com/5396309/44523363-26f77d80-a70c-11e8-8eb4-75047932965d.png)

**Comment by deernano** [comment]
@igarashitm  yes, that's good point~

**Comment by pleacu** [comment]
Hey @deernano - excellent job - I'd like to make a counter proposal to portions of your wire-frame above just to make things simpler.

In this screen capture notice that I have an import icon at the top of both the Source and Targets panels.  This makes it unnecessary for the user to select Sources/Targets in a pop up.  There is no exports icon because it doesn't really make sense for the user to export only a portion of their document model.  Also note that the export icon appears with the main canvas icons - since it makes sense to export at that level.  I've also retained the import/export pulldowns on the main AtlasMap navigation bar since it's a natural place to file them (IMHO).
![i377-1](https://user-images.githubusercontent.com/2981421/44592458-9f9f1e00-a78e-11e8-8d9b-1c34987d0e73.png)

In this capture you'll note that there is no longer a requirement to pick the file format/type.  I'll highlight all JSON/XML files by default (skipping java files for now).  I'll determine how to import the file by its suffix.  Basically all the user needs to specify is teh destination panel - which seems simple enough to not require a whole different popup window.
![i377-2](https://user-images.githubusercontent.com/2981421/44592459-9f9f1e00-a78e-11e8-9603-1ff1c8d28d2e.png)

Once the user selected either Sources or Targets the Import/Cancel buttons appear:
![i377-3](https://user-images.githubusercontent.com/2981421/44592460-9f9f1e00-a78e-11e8-8a1d-4ba417a35ac7.png)

The Export pulldown allows for a simple export the current user mapping (where the file name is suggested by overridable) or an export of instance and schema docs.
![i377-4](https://user-images.githubusercontent.com/2981421/44592461-9f9f1e00-a78e-11e8-8371-9ba5a774efcb.png)

Hover help:
![i377-5](https://user-images.githubusercontent.com/2981421/44592462-9f9f1e00-a78e-11e8-83a7-0cd1e3bff3bb.png)
![i377-6](https://user-images.githubusercontent.com/2981421/44592463-9f9f1e00-a78e-11e8-8964-8e49f75063c2.png)

The file selection popup is standard.  I like the green check marks - I'd like to avoid the continue/confirm all choices by implying the format by the selected suffix.  Also - since export doesn't belong with the panels and import is too complicated if placed with the canvas buttons I'd like to propose that the import/export pulldowns remain on the main navbar.

wdyt?

Thkx!!

**Comment by igarashitm** [comment]
Hi @deernano, I think we have 2 issues here, initial design for standalone only part in UI, and find a room for import/export. I created a separate issue #543 to make it clearer.

**Comment by deernano** [comment]
Hi @pleacu 
The design I proposed is a way that can be used both in standablone and in syndesis. To have an only entry for the user to do import/ export. From UI espect, the only entry is more easy for users to interact with and remember. 

If you feel better to place the icon in the source/ target window, it is better to move the import icon 5-10px left in order to avoid users clicking the wrong icon. 
Also, it is better to place the export icon to the top left as my previous design. Since users are familiar with the current order of those icons. It is better not to place new icon in the old position
![i377-1](https://user-images.githubusercontent.com/2981421/44592458-9f9f1e00-a78e-11e8-8d9b-1c34987d0e73.png)

In patternfly pattern rule,  we only place the most frequently used button and level 1 button on header. It also has an order. You can refer to the below link
https://www.patternfly.org/pattern-library/application-framework/masthead/#design
Normally we place username and question mark on the right.
That's why I recommend to place the button on the toolbar level. 
Also dropdown menu is suitble for the action that does not need to interact with a lot. For example: Simple click and go to the next page, double click (sub level menu) to the next page, checkboxes to choose an action. We do not recommend to place text field and button in dropdown menu.
