### ISSUE TITLE
Standalone UI improvement

### ISSUE THREAD

**Issue by junezhang** [atlasmap/atlasmap#617]
@igarashitm @pleacu 
When checking the demo recording[1], the functionality is great.  
but we found the UI still needs to be improved as following:

- The location of the import/export controls on the Masthead is not matched PatternFly guideline. https://www.patternfly.org/pattern-library/application-framework/masthead/#design
- The behavior and presentation of the drop-down menu is not standard
 
We will help to explore some possibilities to make the UI to be improved.

[1]https://bluejeans.com/playback/s/ribrjgDi81WD136sPUHQ1TPLapi26wnI3NakFQ5KlepoLVhgZN1s8ey6sl4AlWSy

**Comment by pleacu** [comment]
Thanks June - to simplify the UI I was considering removing the import/export pulldowns entirely (solves the masthead issue) and adding an import icon to the main toolbar (next to the existing export icon).  That would result in:

1.  An import icon on the toolbar for importing an .adm mapping file
2.  An export icon on the toolbar for exporting/ creating an .adm file
3.  An import icon on the sources panel
4.  An import icon on the targets panel.

All icons are from patternfly.  If that sounds reasonable I can build/create a screen capture.

**Comment by pleacu** [comment]
Hey June - here is the updated UI:  @junezhang @igarashitm 

![ss1](https://user-images.githubusercontent.com/2981421/46832632-9127b880-cd74-11e8-8165-57236d3e2e93.png)
![ss2](https://user-images.githubusercontent.com/2981421/46832635-938a1280-cd74-11e8-8414-98d8af587efb.png)
![ss3](https://user-images.githubusercontent.com/2981421/46832638-95ec6c80-cd74-11e8-8685-3b26dea7d504.png)
![ss4](https://user-images.githubusercontent.com/2981421/46832651-984ec680-cd74-11e8-88af-94bede46ccb9.png)

**Comment by apupier** [comment]
I'm not UX expert so please check with them but what do you think to put the button bar in the top black bar? it will allow to save space and it seems closer to the image on the Masthead patternfly page:
![image](https://user-images.githubusercontent.com/1105127/46851347-7e09fc80-cdf7-11e8-8bc5-0885c9e99237.png)

Current proposed state is already a great improvement. My proposal can be done (or not) in another iteration (or not).

**Comment by nding-anges** [comment]
Hey @apupier Thanks for your suggestion. From UX point of view, since Import/Export are two key functions and similar level with other actions on top menu, we would like to propose to place these buttons on main top menu with other action buttons together. The buttons on header are a bit far from the source/ target box. Thus, the user may loosing focus. For more detail, you could refer to our previous discussion on relative issues[#377](https://github.com/atlasmap/atlasmap/issues/377) .
As your suggestion, we should also consider optimize space on UI for future improvement, that's a good point of simplicity. :-)

**Comment by nding-anges** [comment]
Thanks Paul for making these changes @pleacu That looks great!  I will send your a new UI design later for next improvement in order to align with PatternFly guideline. It will focus on two UI issues : 
1. UI on Dropdown will align with PatternFly
2. Adding Automatic expand & Toast notification after import/Export action

Thanks~

**Comment by nding-anges** [comment]
@pleacu @junezhang @amysueg Hello everyone, I made the first design proposal for export/import, please find UI screenshot below. 
1. Import/Export button on the main menu is exclusive for import or export entire Altasmaps mapping file , since we have also individually import file function on Source and Target card. 

![import-export1](https://user-images.githubusercontent.com/34368385/46943203-bb91b280-d0a1-11e8-8254-cf254fd86c6e.png)


2. Tooltrip
![import-export2](https://user-images.githubusercontent.com/34368385/46943234-cb10fb80-d0a1-11e8-977b-a8415c328466.png)

3. Using a Pop Over rather than a pop-up when user click Import icon on Source/Target in order to simplifier user's interaction. (recommended)

![import-export3 2x](https://user-images.githubusercontent.com/34368385/46943636-a5d0bd00-d0a2-11e8-870c-3e0038461f90.png)

4.Another posibility is using a Pop-up to show more detail when user click Import icon on Source/Target

![import-export4 2x](https://user-images.githubusercontent.com/34368385/46943655-b3864280-d0a2-11e8-8fe0-c2663ef23b88.png)

WDYT?

**Comment by pleacu** [comment]
@igarashitm  @junezhang @amysueg
Thanks Anges for the design update.  Here are your recommendations with my response:

**1. Import/Export button on the main menu is only for import or export entire Altasmaps mapping file , since we have also individually import file function on Source and Target card.**

I've eliminated the Import/Export pulldowns entirely since their purpose can be accomplished by the 4 icons.  In your design, the new 'Targets' panel icon should read 'Import instance or schema file.'  - It's the same as the import icon for the 'Sources' panel except it's for the Targets panel.   I will add +5px to the gap between the import and export icons on the main toolbar as suggested.

**2.  Tooltip**
Will remain as designed.

**3./4.  Using a Pop Over rather than a pop-up when user click Import icon on Source/Target in order to simplifier user's interaction. (recommended) - more target detail.**

I think that would be a great idea when we support adding .java instance/schemas since the user would need to also specify a java archive as well as a file.  For now - all three import icons go directly to the standard file input dialog which is simple and consistent.  The tooltip reminds them of the type (JSON/XML - Instance/schema) so I think for now that's the best bet.

**Comment by amysueg** [comment]
Thank you @nding-anges and @pleacu 
Just one possible option for helping to separate the import and export icons from the others is to use a vertical pipe as in these examples: https://www.patternfly.org/pattern-library/forms-and-controls/toolbar/

**Comment by nding-anges** [comment]
Thanks, Amy @amysueg and Paul @pleacu. I modified a little bit the wireframe:
1. Adding a vertical pipe between the import and export icons and the others.
![import-export1](https://user-images.githubusercontent.com/34368385/47004399-125fc080-d164-11e8-84a5-ade6b8e87c80.png)

2. Adding a tooltip on Import of Target ( Do we need to write "JSON/XML" on the tooltip? @pleacu )
![import-export2](https://user-images.githubusercontent.com/34368385/47004801-eb55be80-d164-11e8-88f8-d4a6eda60ed5.png)

3.  UI design for Export Pop Over 
![import-export6 2x](https://user-images.githubusercontent.com/34368385/47004826-f577bd00-d164-11e8-93bb-1137cab3e6b6.png)

4. Adding Automatic expand & Toast notification after import/Export action

![import-export7 2x](https://user-images.githubusercontent.com/34368385/47004975-599a8100-d165-11e8-9107-f03bcb4f4a1c.png)

Hi Paul, @pleacu   I have another question: what is going on when a user clicks "Import" on Source. If I well understand, that would not have a drop-down to select the type of file, such as "Instance or schema"," JSON or XML"? Right?

**Comment by pleacu** [comment]
I added the pipe separator.  I'd like to save the export pop-over and adding automatic expand & Toast notification after import/Export action for the next release.  The toolbar import icon is for importing an .adm file only (the result of the export icon).  The import icons on the source and targets panel are for importing json and xml schemas and instances.

![ss1](https://user-images.githubusercontent.com/2981421/47040251-d0c71980-d153-11e8-9337-2ca392a4e410.png)

**Comment by nding-anges** [comment]
Get it! Thanks~ Paul @pleacu
