### ISSUE TITLE
Let user choose if importing Document is schema or instance

### ISSUE THREAD

**Issue by igarashitm** [atlasmap/atlasmap#832]
I found angular.json has `/$schema` property while it still should be treated as a instance document. It might be better to look at the value as well and check if it starts with `http://json-schema.org/schema` to say it's JSON schema.

Furthermore, there could be an usecase to use JSON schema as an instance, so JSON schema is used as a payload. We should let user choose if it's schema or instance. Same for XML, XML schema could be used as an instance.

So instead of opening file dialog directly from + button, we need an intermediate modal which has a toggle to select instance/schema, and file upload.

**Comment by pleacu** [comment]
Currently the XSD/XML decision is based off of the imported document suffix - ref: https://github.com/atlasmap/atlasmap/blob/master/ui/packages/atlasmap-core/src/services/document-management.service.ts#L441

This is wrong, as `SchemaSet` would have `.xml` as an extension. But the content is a set of XML Schema. We should let the user choose if it's instance or schema.

**Comment by pleacu** [comment]
Hey @igarashitm - so here's what I have for setting instance/ schema.
First - you click the import icon on the panel:

![sc1](https://user-images.githubusercontent.com/2981421/108772295-d2c2f380-752a-11eb-93c7-6d49e92b7566.png)

Then you get the instance/schema dialog:

![sc2](https://user-images.githubusercontent.com/2981421/108772347-e40c0000-752a-11eb-80d0-951d1331b5dc.png)

Notice in this example it defaults to schema since the file suffix is `xsd`.  It doesn't open the file and look for `SchemaSet` or `$schema` any more.  The import won't occur until the user clicks `OK`.  Does that look about right?  Any changes to text, etc?
thkx

**Comment by igarashitm** [comment]
LGTM - I would avoid the word "instance-schema", we use the instance document to only "assume" the schema, but it might not be exactly correct.
