### ISSUE TITLE
Transformation not as expected when mapping a constant/property into an element inside array

### ISSUE THREAD

**Issue by AbbassFaytaroony** [atlasmap/atlasmap#959]
When mapping a constant to an element in a json array, example: if i map a constant to "id" property in the following target document :
```
{
 "elements":[
    {
      "id":"123",
      "properties":{
        "property1":"value1",
        "property2":"value2"
      }
    },    {
      "id":"456",
      "properties":{
        "property1":"value1",
        "property2":"value2"
      }
    }
  ]

}
```
During transformation, and knowing that input document is also JSON array in the form:
```
[
  {
    "property1": "value1",
    "property2": "value2"
  },
  {
    "property1": "value1",
    "property2": "value2"
  }
]
```
The constant i mapped only appears in the first array element of the output, whereas i expect it to appear in all array elements

**Comment by igarashitm** [comment]
This might be like `forEach` one-to-many transformation.

The tricky part is that, the number of element is determined at runtime, which depends on other mapping entries. Unless other mapping creates multiple elements, this specific `constant => array[]` mapping only creates one element in the array. Therefore, the mapping involves `forEach` one-to-many transformation requires one of following two:
1. It should be processed last, so that the other entries can determine the number of array elements
1. The `forEach` transformation should be able to register some kind of "hook" to specify default value of the element

Both of them requires some level of refactoring in the core.
